### ISSUE TITLE
Update Project Link in Readme

### ISSUE THREAD

**Issue by PeterShaggyNoble** [damianobarbati/muicons#1]
I notice you're linking to my MDI-Sandbox project as the source for Material Design Icons but please note that the official website is https://materialdesignicons.com/ - can you update your Readme file to reflect that, please?

**Comment by damianobarbati** [comment]
Sorry @PeterShaggyNoble, I didn't have notifications on this repo. Fixing it asap

**Comment by damianobarbati** [comment]
@PeterShaggyNoble done: can you confirm the ref section in the README is fine now?
